"""CoSyNe keyword taxonomy, copied verbatim from the CoSyNe analysis (analyze_v2.py).

Kept identical so the CoSyNe x CNS contrast (Module E) is apples-to-apples.
KEYWORDS maps a canonical term to its synonym list; CATEGORIES groups canonical terms.
"""

KEYWORDS = {
    # AI/ML Methods
    "deep learning": ["deep learning", "deep neural network", "deep network"],
    "RNN": ["recurrent neural network", "rnn", "recurrent network", "recurrent model"],
    "transformer": ["transformer", "attention mechanism", "self-attention"],
    "foundation model": ["foundation model", "pretrained model", "pre-trained model"],
    "self-supervised": ["self-supervised", "self supervised", "contrastive learning"],
    "LLM": ["large language model", "llm", "language model"],
    "reinforcement learning": [
        "reinforcement learning",
        "reward learning",
        "reward prediction error",
        "temporal difference",
    ],
    "generative model": [
        "generative model",
        "variational autoencoder",
        "vae",
        "generative adversarial",
        "diffusion model",
    ],
    "backpropagation": ["backpropagation", "backprop", "error backpropagation", "gradient descent"],
    # Core Computational Neuroscience
    "Bayesian": ["bayesian", "prior distribution", "posterior distribution", "bayesian inference"],
    "population": [
        "population coding",
        "population activity",
        "population dynamics",
        "neural population",
    ],
    "circuit": [
        "neural circuit",
        "circuit model",
        "circuit mechanism",
        "microcircuit",
        "cortical circuit",
    ],
    "plasticity": [
        "plasticity",
        "synaptic plasticity",
        "hebbian",
        "long-term potentiation",
        "long-term depression",
        "stdp",
    ],
    "decision": ["decision making", "decision-making", "perceptual decision", "evidence accumulation"],
    "latent": ["latent variable", "latent space", "latent dynamics", "latent factor", "latent state"],
    "manifold": ["manifold", "low-dimensional", "low dimensional", "neural manifold"],
    "dimensionality": [
        "dimensionality reduction",
        "dimensionality",
        "high-dimensional",
        "high dimensional",
    ],
    "recurrence": [
        "recurrent dynamics",
        "attractor",
        "attractor network",
        "fixed point",
        "dynamical system",
    ],
    "predictive coding": ["predictive coding", "prediction error", "predictive processing"],
    "information theory": [
        "mutual information",
        "information theory",
        "information processing",
        "fisher information",
    ],
    "oscillation": [
        "oscillation",
        "oscillatory",
        "gamma oscillation",
        "theta oscillation",
        "neural oscillation",
    ],
    "working memory": ["working memory", "short-term memory", "persistent activity"],
    "navigation": [
        "navigation",
        "place cell",
        "grid cell",
        "spatial representation",
        "hippocampal map",
        "cognitive map",
    ],
    "compositionality": [
        "compositionality",
        "compositional",
        "systematic generalization",
        "abstract rule",
    ],
    # Experimental Methods
    "optogenetics": ["optogenetics", "optogenetic", "channelrhodopsin", "photostimulation"],
    "Neuropixels": ["neuropixels", "neuropixel", "high-density probe", "high density probe"],
    "calcium imaging": ["calcium imaging", "two-photon", "2-photon", "gcamp", "miniscope"],
    "connectomics": [
        "connectome",
        "connectomics",
        "electron microscopy",
        "synaptic connectivity map",
    ],
    "fMRI": ["fmri", "functional magnetic resonance", "bold signal", "neuroimaging"],
    # Model Organisms
    "mouse": ["mouse", "mice", "murine"],
    "primate": ["primate", "monkey", "macaque", "non-human primate"],
    "Drosophila": ["drosophila", "fruit fly", "fly brain"],
    "behavior": ["behavior", "behaviour", "behavioral", "behavioural"],
    # Emerging
    "interpretability": [
        "interpretability",
        "interpretable",
        "mechanistic interpretability",
        "explainability",
    ],
    "neuromodulation": [
        "neuromodulation",
        "neuromodulatory",
        "dopamine",
        "serotonin",
        "acetylcholine",
        "norepinephrine",
    ],
    "dendritic": ["dendritic", "dendrite", "dendritic computation", "dendritic integration"],
    "naturalistic": [
        "naturalistic",
        "natural behavior",
        "natural scene",
        "ethological",
        "freely moving",
    ],
    "sequence": ["sequence learning", "sequence", "sequential", "temporal sequence"],
    "embodiment": ["embodiment", "embodied", "sensorimotor"],
    # Sensory & Cognitive Domains
    "visual": [
        "visual cortex",
        "visual system",
        "visual processing",
        "visual stimulus",
        "visual response",
    ],
    "auditory": [
        "auditory cortex",
        "auditory system",
        "auditory processing",
        "auditory stimulus",
        "sound processing",
    ],
    "spiking": ["spiking network", "spiking neuron", "spike train", "spiking model", "spike timing"],
    # Neural Computations
    "inhibition": [
        "inhibition",
        "inhibitory",
        "interneuron",
        "gabaergic",
        "e-i balance",
        "excitatory-inhibitory",
    ],
    "adaptation": ["adaptation", "neural adaptation", "sensory adaptation", "adaptive"],
    "noise": [
        "neural noise",
        "noise correlation",
        "trial-to-trial variability",
        "neural variability",
        "stochastic",
    ],
    "encoding/decoding": [
        "neural coding",
        "neural code",
        "population decoding",
        "encoding model",
        "decoding accuracy",
    ],
    "normalization": ["divisive normalization", "gain control", "normalization", "gain modulation"],
    "sparse coding": ["sparse coding", "sparse representation", "sparsity", "sparse activity"],
    "feedforward": ["feedforward", "feed-forward", "feedforward network"],
    "hierarchy": ["hierarchy", "hierarchical", "hierarchical processing", "cortical hierarchy"],
    # Brain Regions
    "cortex": ["cortex", "cortical", "neocortex", "neocortical"],
    "hippocampus": ["hippocampus", "hippocampal", "dentate gyrus"],
    "prefrontal": ["prefrontal", "prefrontal cortex", "dlpfc", "orbitofrontal"],
    # Biology & Evolution
    "development": ["development", "developmental", "maturation", "critical period"],
    "evolution": ["evolution", "evolutionary", "evolved", "phylogenetic"],
}

CATEGORIES = {
    "AI/ML Methods": [
        "deep learning",
        "RNN",
        "transformer",
        "foundation model",
        "self-supervised",
        "LLM",
        "reinforcement learning",
        "generative model",
        "backpropagation",
    ],
    "Core Concepts": [
        "Bayesian",
        "population",
        "circuit",
        "plasticity",
        "decision",
        "latent",
        "manifold",
        "dimensionality",
        "recurrence",
        "predictive coding",
        "information theory",
        "oscillation",
        "working memory",
        "navigation",
        "compositionality",
        "inhibition",
        "adaptation",
        "noise",
        "encoding/decoding",
        "normalization",
        "sparse coding",
        "feedforward",
        "hierarchy",
    ],
    "Experimental Tech": ["optogenetics", "Neuropixels", "calcium imaging", "connectomics", "fMRI"],
    "Model Systems": ["mouse", "primate", "Drosophila", "behavior"],
    "Sensory & Brain": ["visual", "auditory", "spiking", "cortex", "hippocampus", "prefrontal"],
    "Emerging Topics": [
        "interpretability",
        "neuromodulation",
        "dendritic",
        "naturalistic",
        "sequence",
        "embodiment",
        "development",
        "evolution",
    ],
}
